import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  tutorialSidebar: [
    {
      "type": "category",
      "label": "Home",
      "items": [
        {
          "type": "doc",
          "label": "Welcome",
          "id": "home/welcome"
        },
        {
          "type": "doc",
          "label": "What's New in PoT",
          "id": "home/whats-new"
        }
        // {
        //   "type": "doc",
        //   "label": "What's Next",
        //   "id": "home/whats-next"
        // }
      ]
    },
    {
      "type": "category",
      "label": "Getting Started",
      "items": [
        // {
        //   "type": "doc",
        //   "label": "What's New in ioFog 3.0.0?",
        //   "id": "getting-started/whats-new"
        // },
        {
          "type": "doc",
          "label": "Core Concepts",
          "id": "getting-started/core-concepts"
        },
        {
          "type": "doc",
          "label": "Architecture",
          "id": "getting-started/architecture"
        },
        {
          "type": "doc",
          "label": "Quick Start With Local Deployment",
          "id": "getting-started/quick-start-local"
        }
        // {
        //   "type": "doc",
        //   "label": "Quick Start On Minikube and Vagrant",
        //   "id": "getting-started/quick-start-minikube"
        // }
      ]
    },
    {
      "type": "category",
      "label": "potctl",
      "items": [
        {
          "type": "doc",
          "label": "Introduction",
          "id": "potctl/introduction"
        },
        {
          "type": "doc",
          "label": "Download",
          "id": "potctl/download"
        },
        {
          "type": "doc",
          "label": "Getting Familiar",
          "id": "potctl/getting-familiar"
        },
        {
          "type": "doc",
          "label": "Resource Management",
          "id": "potctl/resource-management"
        },
        {
          "type": "doc",
          "label": "Connect/Disconnect",
          "id": "potctl/connect-disconnect"
        },
        {
          "type": "doc",
          "label": "Legacy",
          "id": "potctl/legacy"
        },
        {
          "type": "category",
          "label": "CLI Reference",
          "link": {
            "type": "doc",
            "id": "potctl/cli/potctl"
          },
          "items": [
            { "type": "autogenerated", "dirName": "potctl/cli" }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Platform Deployment",
      "items": [
        {
          "type": "doc",
          "label": "Introduction",
          "id": "platform-deployment/introduction"
        },
        {
          "type": "doc",
          "label": "Prepare Your Network",
          "id": "platform-deployment/prepare-your-network"
        },
        {
          "type": "doc",
          "label": "Prepare Realm and OIDC Client",
          "id": "platform-deployment/prepare-realm"
        },
        {
          "type": "doc",
          "label": "Keycloak Deployment",
          "id": "platform-deployment/keycloak-deployment"
        },
        {
          "type": "doc",
          "label": "Prepare Your Remote Hosts",
          "id": "platform-deployment/prepare-your-remote-hosts"
        },
        {
          "type": "doc",
          "label": "Remote Control Plane",
          "id": "platform-deployment/remote-control-plane"
        },
        {
          "type": "doc",
          "label": "Kubernetes Prepare Cluster",
          "id": "platform-deployment/kubernetes-prepare-cluster"
        },
        {
          "type": "doc",
          "label": "External Database Deployment",
          "id": "platform-deployment/database"
        },
        {
          "type": "doc",
          "label": "Kubernetes potctl",
          "id": "platform-deployment/kubernetes-potctl"
        },
        {
          "type": "doc",
          "label": "Kubernetes Helm",
          "id": "platform-deployment/kubernetes-helm"
        },
        {
          "type": "doc",
          "label": "Setup Your Agents",
          "id": "platform-deployment/setup-your-agents"
        },
        {
          "type": "doc",
          "label": "Airgap Deployment",
          "id": "platform-deployment/airgap-deployment"
        }
      ]
    },
    {
      "type": "category",
      "label": "Security and RBAC",
      "items": [
        {
          "type": "doc",
          "label": "Securing Cluster",
          "id": "security/introduction"
        },
        {
          "type": "doc",
          "label": "Roles",
          "id": "security/roles"
        },
        {
          "type": "doc",
          "label": "Role Bindings",
          "id": "security/role-bindings"
        },
        {
          "type": "doc",
          "label": "Certificates Manager",
          "id": "security/certificates-manager"
        },
        {
          "type": "doc",
          "label": "NATs Account Rule",
          "id": "security/nats-account-rule"
        },
        {
          "type": "doc",
          "label": "NATs User Rule",
          "id": "security/nats-user-rule"
        },
        {
          "type": "doc",
          "label": "NATs JWT Authentication",
          "id": "security/nats-jwt-authentication"
        },
      ]
    },
    {
      "type": "category",
      "label": "Agent Management",
      "items": [
        {
          "type": "doc",
          "label": "Introduction",
          "id": "agent-management/introduction"
        },
        {
          "type": "doc",
          "label": "Agent Configuration",
          "id": "agent-management/agent-configuration"
        },
        {
          "type": "doc",
          "label": "Attach/Detach",
          "id": "agent-management/attach-detach"
        },
        {
          "type": "doc",
          "label": "Volumes",
          "id": "agent-management/volumes"
        },
        {
          "type": "doc",
          "label": "Docker Image Pruning",
          "id": "agent-management/docker-image-pruning"
        },
        // {
        //   "type": "doc",
        //   "label": "Edge Resources",
        //   "id": "agent-management/edge-resources"
        // },
        {
          "type": "doc",
          "label": "Upgrade/Rollback",
          "id": "agent-management/upgrade-rollback"
        }
      ]
    },
    // {
    //   "type": "category",
    //   "label": "Developing Microservices",
    //   "items": [
    //     {
    //       "type": "doc",
    //       "label": "Overview",
    //       "id": "developing-microservices/overview"
    //     },
    //     {
    //       "type": "doc",
    //       "label": "SDK",
    //       "id": "developing-microservices/sdk"
    //     },
    //     {
    //       "type": "doc",
    //       "label": "Debugging",
    //       "id": "developing-microservices/debugging"
    //     }
    //   ]
    // },
    // {
    //   "type": "category",
    //   "label": "Tutorial - Our First Microservices",
    //   "items": [
    //     {
    //       "type": "doc",
    //       "label": "Introduction",
    //       "id": "tutorial/introduction"
    //     },
    //     {
    //       "type": "doc",
    //       "label": "Get to Know ioFog",
    //       "id": "tutorial/get-to-know-iofog"
    //     },
    //     {
    //       "type": "doc",
    //       "label": "Manage Our Microservices",
    //       "id": "tutorial/manage-our-microservices"
    //     },
    //     {
    //       "type": "doc",
    //       "label": "Create Our First Microservice (JavaScript)",
    //       "id": "tutorial/create-our-first-microservice-javascript"
    //     },
    //     {
    //       "type": "doc",
    //       "label": "Deploy Our Microservice",
    //       "id": "tutorial/deploy-our-microservice"
    //     }
    //   ]
    // },
    {
      "type": "category",
      "label": "Application Management",
      "items": [
        {
          "type": "doc",
          "label": "Introduction",
          "id": "applications/introduction"
        },
        {
          "type": "doc",
          "label": "Application Templates",
          "id": "applications/application-templates"
        },
        {
          "type": "doc",
          "label": "Microservice Lifecycle Management",
          "id": "applications/microservice-lifecycle-management"
        },
        {
          "type": "doc",
          "label": "Microservice Logs",
          "id": "applications/microservice-logs"
        },
        {
          "type": "doc",
          "label": "Microservice Move/Rename",
          "id": "applications/microservice-move-rename"
        },
        {
          "type": "doc",
          "label": "Microservice Registry Catalog",
          "id": "applications/microservice-registry-catalog"
        }
      ]
    },
    {
      "type": "category",
      "label": "YAML References",
      "items": [
        {
          "type": "doc",
          "label": "YAML Kinds",
          "id": "yaml-references/reference-kinds"
        },
        {
          "type": "doc",
          "label": "Control Plane",
          "id": "yaml-references/reference-control-plane"
        },
        {
          "type": "doc",
          "label": "Agent",
          "id": "yaml-references/reference-agent"
        },
        {
          "type": "doc",
          "label": "Application",
          "id": "yaml-references/reference-application"
        },
        {
          "type": "doc",
          "label": "Application Template",
          "id": "yaml-references/reference-application-template"
        },
        {
          "type": "doc",
          "label": "Registry",
          "id": "yaml-references/reference-registry"
        },
        {
          "type": "doc",
          "label": "Catalog",
          "id": "yaml-references/reference-catalog"
        },
        {
          "type": "doc",
          "label": "OfflineImage",
          "id": "yaml-references/reference-offlineimage"
        },
        {
          "type": "doc",
          "label": "Secret",
          "id": "yaml-references/reference-secret"
        },
        {
          "type": "doc",
          "label": "Certificate",
          "id": "yaml-references/reference-certificate"
        },
        {
          "type": "doc",
          "label": "ConfigMap",
          "id": "yaml-references/reference-configmap"
        },
        {
          "type": "doc",
          "label": "VolumeMount",
          "id": "yaml-references/reference-volumemount"
        },
        {
          "type": "doc",
          "label": "Service",
          "id": "yaml-references/reference-service"
        },
        {
          "type": "doc",
          "label": "Role",
          "id": "yaml-references/reference-roles"
        },
        {
          "type": "doc",
          "label": "RoleBinding",
          "id": "yaml-references/reference-role-binding"
        },
        {
          "type": "doc",
          "label": "NatsAccountRule",
          "id": "yaml-references/reference-nats-account-rule"
        },
        {
          "type": "doc",
          "label": "NatsUserRule",
          "id": "yaml-references/reference-nats-user-rule"
        }
        // {
        //   "type": "doc",
        //   "label": "Edge Resources",
        //   "id": "yaml-references/reference-edge-resources"
        // }
        // {
        //   "type": "doc",
        //   "label": "Template Engine",
        //   "id": "yaml-references/reference-template-engine"
        // }
      ]
    },
    {
      "type": "category",
      "label": "ECN Viewer",
      "items": [
        {
          "type": "doc",
          "label": "ECN Viewer",
          "id": "ECN-Viewer/ecn-viewer"
        }
      ]
    },
    {
      "type": "category",
      "label": "Reference - Controller",
      "items": [
        {
          "type": "doc",
          "label": "Overview",
          "id": "reference-controller/overview"
        },
        {
          "type": "doc",
          "label": "Configuration",
          "id": "reference-controller/configuration"
        },
        // {
        //   "type": "doc",
        //   "label": "CLI Usage",
        //   "id": "reference-controller/cli-usage"
        // },
        {
          "type": "doc",
          "label": "REST API",
          "id": "reference-controller/rest-api"
        }
      ]
    },
    {
      "type": "category",
      "label": "Reference - Agent",
      "items": [
        {
          "type": "doc",
          "label": "Overview",
          "id": "reference-agent/overview"
        },
        {
          "type": "doc",
          "label": "CLI Usage",
          "id": "reference-agent/cli-usage"
        },
        {
          "type": "doc",
          "label": "Local API",
          "id": "reference-agent/local-api"
        },
        {
          "type": "doc",
          "label": "Configuration",
          "id": "reference-agent/configuration"
        },
        {
          "type": "doc",
          "label": "Agent Logs",
          "id": "reference-agent/agent-logs"
        }
      ]
    },
    {
      "type": "category",
      "label": "Reference - Catalog Microservices",
      "items": [
        // {
        //   "type": "doc",
        //   "label": "NATs",
        //   "id": "reference-microservices-catalog/nats"
        // },
        {
          "type": "doc",
          "label": "HAL",
          "id": "reference-microservices-catalog/hal"
        },
        {
          "type": "doc",
          "label": "REST Blue",
          "id": "reference-microservices-catalog/rest-blue"
        }
        // {
        //   "type": "doc",
        //   "label": "Proxus IIoT Platform",
        //   "id": "reference-microservices-catalog/Proxus-IIoT"
        // }
        // {
        //   "type": "doc",
        //   "label": "Diagnostics",
        //   "id": "reference-microservices-catalog/diagnostics"
        // },
        // {
        //   "type": "doc",
        //   "label": "JSON REST API",
        //   "id": "reference-microservices-catalog/jsonrestapi"
        // }
      ]
    }
    // {
    //   "type": "category",
    //   "label": "Contributing",
    //   "items": [
    //     {
    //       "type": "doc",
    //       "label": "Guidelines",
    //       "id": "contributing/guidelines"
    //     },
    //     {
    //       "type": "doc",
    //       "label": "Code of Conduct",
    //       "id": "contributing/code-of-conduct"
    //     }
    //   ]
    // }
  ]
};

export default sidebars;
