export type Distribution = 'datasance' | 'iofog';

export const FLAVOR: Distribution =
  (process.env.DOCUSAURUS_DISTRIBUTION as Distribution) ?? 'datasance';

export const PRODUCT_NAME =
  FLAVOR === 'datasance' ? 'Datasance PoT' : 'Eclipse ioFog';

export const API_VERSION =
  FLAVOR === 'datasance' ? 'datasance.com/v3' : 'iofog.org/v3';

export const REGISTRY = `ghcr.io/${FLAVOR === 'datasance' ? 'datasance' : 'eclipse-iofog'}`;

export const HELM_REPO_URL =
  FLAVOR === 'datasance'
    ? 'https://datasance.github.io/iofog-operator'
    : 'https://eclipse-iofog.github.io/iofog-operator';

export const OPERATOR_CHART_README_URL =
  FLAVOR === 'datasance'
    ? 'https://github.com/Datasance/iofog-operator/blob/develop/charts/iofog-operator/README.md'
    : 'https://github.com/eclipse-iofog/iofog-operator/blob/develop/charts/iofog-operator/README.md';

export const OPERATOR_CHART_VALUES_SCHEMA_URL = OPERATOR_CHART_README_URL.replace(
  '/README.md',
  '/values.schema.json',
);

export const CONTROLPLANE_CRD_RESOURCE =
  FLAVOR === 'datasance' ? 'controlplanes.datasance.com' : 'controlplanes.iofog.org';

/** Helm chart version aligned with platform train v3.9.0 operator release. */
export const OPERATOR_CHART_VERSION = '3.9.0';

/** Platform train version (Controller, Router, CLI). */
export const PLATFORM_TRAIN = '3.9.0';

/** Edgelet binary and container image tag for the current platform train. */
export const EDGELET_VERSION = '1.1.0';

export const CLI_NAME = FLAVOR === 'datasance' ? 'potctl' : 'iofogctl';

/** Narrative CLI guides (introduction, download, and the other primer pages). */
export const CLI_GUIDES_DIR = 'get-started/cli';

/** Autogenerated CLI command reference (`reference/cli/potctl` vs `reference/cli/iofogctl`). */
export const CLI_DOCS_DIR = FLAVOR === 'datasance' ? 'reference/cli/potctl' : 'reference/cli/iofogctl';

/** Platform train table row on Welcome. */
export const PLATFORM_TRAIN_LABEL =
  FLAVOR === 'datasance' ? 'PoT platform' : 'Platform';

/** Docusaurus `baseUrl` (trailing slash). */
export const BASE_PATH = FLAVOR === 'iofog' ? '/iofog/' : '/';

export const NAVBAR_LOGO = {
  src: FLAVOR === 'datasance' ? 'img/logo.svg' : 'img/iofog-logo.svg',
  srcDark: FLAVOR === 'datasance' ? 'img/logo-white.svg' : 'img/iofog-logo.svg',
};

/** Light wordmarks for the marketing homepage hero (not the navbar marks). */
export const HERO_LOGO = {
  src: FLAVOR === 'datasance' ? 'img/logo-white.svg' : 'img/iofog-logo-white.svg',
};

export const SITE_TAGLINE =
  FLAVOR === 'datasance'
    ? 'Securely deploy, manage, and scale containerized workloads and AI applications across thousands of heterogeneous far-edge and IoT environments.'
    : 'Securely deploy, orchestrate, and operate distributed workloads across your edge environment from a single control plane with Eclipse ioFog.';

export const GITHUB_ORG_URL =
  FLAVOR === 'datasance'
    ? 'https://github.com/Datasance'
    : 'https://github.com/eclipse-iofog';

/** Embedded Edgelet bootstrap assets in the CLI repo (`develop` branch). */
export const CLI_REPO_EDGELET_ASSETS_URL = `${GITHUB_ORG_URL}/${CLI_NAME}/tree/develop/assets/edgelet`;

/** Serialized into Docusaurus `customFields` for client components (homepage, theme). */
export function getSiteCustomFields() {
  return {
    distribution: FLAVOR,
    productName: PRODUCT_NAME,
    cliName: CLI_NAME,
    cliGuidesDir: CLI_GUIDES_DIR,
    cliReferenceDir: CLI_DOCS_DIR,
    platformTrain: PLATFORM_TRAIN,
    edgeletVersion: EDGELET_VERSION,
    platformTrainLabel: PLATFORM_TRAIN_LABEL,
    githubOrgUrl: GITHUB_ORG_URL,
    heroLogoSrc: HERO_LOGO.src,
    siteTagline: SITE_TAGLINE,
  } as const;
}

export const FAVICON =
  FLAVOR === 'datasance' ? 'img/favicon.ico' : 'img/iofog-favicon.png';

/** Open Graph / Twitter card. PNG so link unfurlers can render it. */
export const SOCIAL_CARD_IMAGE =
  FLAVOR === 'datasance' ? 'img/datasance-logo.png' : 'img/iofog-social-card.png';

export const SITE_KEYWORDS =
  FLAVOR === 'datasance'
    ? 'edge computing, edgeops, distributed edge computing, datasance pot, pot, fog computing, kubernetes edge, iofog, iot platform, edge orchestration'
    : 'edge computing, eclipse iofog, iofog, fog computing, kubernetes edge, iot platform, edge orchestration, distributed edge computing';

export const LINKEDIN_URL = 'https://www.linkedin.com/company/datasance';

export const TRIAL_URL = 'https://www.datasance.com/trial';

export const SHOW_TRIAL_CTA = FLAVOR === 'datasance';

export const SHOW_LINKEDIN = FLAVOR === 'datasance';

export const COPYRIGHT_HREF =
  FLAVOR === 'datasance' ? 'https://www.datasance.com' : 'https://iofog.org';

export const COPYRIGHT_LABEL =
  FLAVOR === 'datasance' ? 'Datasance' : 'Eclipse ioFog';

/** Footer copyright line (same text on both flavors). */
export const FOOTER_COPYRIGHT = 'Copyright © 2026 Datasance Built with Docusaurus.';
