import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

export type SiteFlavorFields = {
  distribution: 'datasance' | 'iofog';
  productName: string;
  cliName: string;
  /** Route prefix for narrative CLI guides. */
  cliGuidesDir: string;
  /** Route prefix for autogenerated CLI reference. */
  cliReferenceDir: string;
  platformTrainLabel: string;
  githubOrgUrl: string;
  heroLogoSrc: string;
  siteTagline: string;
};

export function useSiteFlavor(): SiteFlavorFields {
  const {siteConfig} = useDocusaurusContext();
  return siteConfig.customFields as SiteFlavorFields;
}
